### ISSUE TITLE
Expected range of edge scores

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ssps#10]
Are the output edge scores supposed to fall in the range (0, 1)?  In some runs, such as this [CI job](https://travis-ci.com/github/gitter-lab/ssps/jobs/332195219#L1129), edges have a score > 1.

**Comment by dpmerrell** [comment]
Hmmm, good catch. The scores should be in [0, 1]. 

This is most likely due to an off-by-one error in the denominator when I compute probabilities (count / total number of steps). I'll check whether that's true and fix it up.

The good news is that this doesn't make any difference in any of our evaluations (neither notion of AUPRC requires probabilities in [0,1]).
